### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property loadPaymentDataResult has not been initialized

### ISSUE THREAD

**Issue by AndriiChemer** [PayU-EMEA/PayU-Flutter#26]
Hi, I have issue with google pay payment. 

**My steps:**
1. Initialized library. 
2. Create PaymentMethodsConfiguration
3. Select PaymentMethod from PaymentMethodsWidget and execute it using PaymentMethodsProcessor().process().
4. await payments.canMakePayment(paymentConfiguration) executed with success.
5. await payments.makePayment(paymentConfiguration); executed with success, but after that my app crashes

**I have got such error log:** 
kotlin.UninitializedPropertyAccessException: lateinit property loadPaymentDataResult has not been initialized
E/AndroidRuntime(17456): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5311)
E/AndroidRuntime(17456): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5350)
E/AndroidRuntime(17456): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime(17456): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(17456): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17456): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17456): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
E/AndroidRuntime(17456): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17456): 	at android.os.Looper.loopOnce(Looper.java:346)
E/AndroidRuntime(17456): 	at android.os.Looper.loop(Looper.java:475)
E/AndroidRuntime(17456): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/AndroidRuntime(17456): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
E/AndroidRuntime(17456): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property loadPaymentDataResult has not been initialized
E/AndroidRuntime(17456): 	at io.flutter.plugins.pay_android.GooglePayHandler.handlePaymentSuccess(GooglePayHandler.kt:216)
E/AndroidRuntime(17456): 	at io.flutter.plugins.pay_android.GooglePayHandler.onActivityResult(GooglePayHandler.kt:180)
E/AndroidRuntime(17456): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:774)
E/AndroidRuntime(17456): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:422)
E/AndroidRuntime(17456): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:857)
E/AndroidRuntime(17456): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:1251)
E/AndroidRuntime(17456): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:653)
E/AndroidRuntime(17456): 	at android.app.Activity.dispatchActivityResult(Activity.java:8381)
E/AndroidRuntime(17456): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5304)
E/AndroidRuntime(17456): 	... 13 more

**Comment by AndriiChemer** [comment]
The problem was in pay library. I just tried to implement few payment system in one app, and there was added pay library and it was the problem of that crash.
